---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gol-deploy
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: gol
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: gol-pod
      labels:
        app: gol
    spec:
      containers:
        - name: gol
          image: gol:1.0
      imagePullSecrets:
        - name: mycred
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            tcpSocket:
              port: 8080

---
apiVersion: v1 
kind: Service
metadata:
  name: gol-svc
spec:
  type: LoadBalancer
  selector:
    app: gol
  ports:
    - name: webport
      port: 35000
      targetPort: 8080
    
